### ISSUE TITLE
Data loading code is not there for training on opendialkg

### ISSUE THREAD

**Issue by rashad101** [fabiangal/space-efficient-context-encoding-acl21#1]
I tried to run the training script with the following command:
`python train.py --dataset opendialkg --depth 0 --encoding series`

I am getting this error:
`Argument dataset=opendialkg is not valid!`

I think its because of the missing data loading code for the opendialkg here: (https://github.com/fabiangal/space-efficient-context-encoding-acl21/blob/fa95c2f1e1f17c49006125b5babe2242f696ded9/train.py#L85)

Could you update the training script with the code that handles opendialkg?

**Comment by fabiangal** [comment]
Hey,

I'll have a look at this as soon as possible. Sorry for that!

Best regards,

Fabian

**Comment by fabiangal** [comment]
OpenDialKG training should work now.
